# Generated by Django 4.2.1 on 2023-05-25 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("vendor", models.CharField(max_length=255)),
                ("currency_a", models.CharField(max_length=3)),
                ("currency_b", models.CharField(max_length=3)),
                ("sell", models.DecimalField(decimal_places=10, max_digits=15)),
                ("buy", models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name="rate",
            constraint=models.UniqueConstraint(
                fields=("date", "vendor", "currency_a", "currency_b"),
                name="unique_rate",
            ),
        ),
    ]
